wandb_version: 1

model:
  desc: null
  value: LLaMA 2 13B, Raw
lr:
  desc: null
  value: 3.0e-05
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.1
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700976164.384819
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.1
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
